[profile.default]
  libs = ["lib"]
  out = "out"
  remappings = [
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "src/=src/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
  ]
  src = "src"

  [rpc_endpoints]
  base_mainnet = "https://mainnet.base.org/"

  # See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
